FROM osrm/osrm-backend as test

COPY geo/oberbayern-latest.osm.pbf /data/map.osm.pbf
COPY bike.lua /opt/bike.lua
RUN osrm-extract -p /opt/bike.lua /data/map.osm.pbf
RUN osrm-partition /data/map.osm.pbf
RUN osrm-customize /data/map.osm.pbf

ENV PORT 8080

CMD osrm-routed --algorithm mld --port $PORT /data/map.osrm